// <auto-generated />
using Dream.API.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dream.API.Migrations
{
    [DbContext(typeof(DreamApiDbContext))]
    [Migration("20231005082515__Add_First_Data")]
    partial class _Add_First_Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Dream.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Capital City!",
                            Name = "Tehran"
                        },
                        new
                        {
                            Id = 2,
                            Description = "a Large City",
                            Name = "Shiraz"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Half of the World :))",
                            Name = "Esfahan"
                        },
                        new
                        {
                            Id = 4,
                            Description = "a Shit one...",
                            Name = "Mashhad"
                        });
                });

            modelBuilder.Entity("Dream.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Point Of Interest Tehran",
                            Name = "Point Of Interest Tehran"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Description = "Point Of Interest Shiraz",
                            Name = "Point Of Interest Shiraz"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Description = "Point Of Interest Esfahan",
                            Name = "Point Of Interest Esfahan"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Description = "Point Of Interest Mashhad",
                            Name = "Point Of Interest Mashhad"
                        });
                });

            modelBuilder.Entity("Dream.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("Dream.API.Entities.City", "City")
                        .WithMany("PointOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Dream.API.Entities.City", b =>
                {
                    b.Navigation("PointOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
